/*
 * @Descripttion:
 * @Author: shenqiang
 * @Date: 2021-12-13 11:43:54
 * @LastEditors: shenqiang
 * @LastEditTime: 2021-12-18 10:40:36
 */
// import request from '@/utils/request'
export function testInfo() {
  // return request({
  //   url: `/test/testInfo`,
  //   method: 'get'
  // })
  return new Promise(resolve => {
    resolve({
      body: {
        accountId: 1,
        authorities: [
          'productManage',
          'rcBasic',
          'qks',
          'rcsLaw',
          'rccaAdd',
          'rccArticle',
          'rcContent',
          'rcSetting',
          'dashboard',
          'runCenter',
          'workStation',
          'pcbmAirCompany',
          'pcpiSite',
          'wswApplyDetail',
          'pcsmTrainAdd',
          'pcsmiDel',
          'pcrspAdd',
          'pcsmInsurance',
          'pcrsfEdit',
          'pcsmbAdd',
          'pcBaseManage',
          'pcrstDelTag',
          'pcpmpmCopy',
          'pcbmacValid',
          'pcpmpmUpDown',
          'pcPublicInformation',
          'pcpifAdd',
          'productCenter',
          'pcpiSiteAdd',
          'pcpmpmAdd',
          'pcbmtcLog',
          'pcsmTicketValid',
          'wswApprove',
          'pcsmhLog',
          'pcrstDelGroup',
          'pcrstLog',
          'pcsmpLog',
          'pcbmtcValid',
          'pcsmTrain',
          'pcsmiValid',
          'pcpiFood',
          'pcrstAddGroup',
          'pcpiShopDel',
          'pcpmProductManage',
          'pcProductManage',
          'pcbmtcAdd',
          'pcpifEdit',
          'pcrstEditGroup',
          'pcbmtcEdit',
          'pcbmsAdd',
          'pcpiSiteEdit',
          'pcpifDel',
          'pcrsfAdd',
          'pcpiSiteDel',
          'pcpiShopValid',
          'pcrsFacility',
          'pcpmpmAudit',
          'pcbmacDel',
          'pcsmhEdit',
          'pcsmhValid',
          'pcsmTicketDel',
          'pcsmhDel',
          'pcsmbValid',
          'pcrspDel',
          'pcsmpDel',
          'pcsmbLog',
          'pcbmStation',
          'pcrstValid',
          'pcsmTrainEdit',
          'pcpiSiteValid',
          'pcsmiAdd',
          'pcsmBus',
          'pcpmpmDel',
          'pcResourceSet',
          'pcpifLog',
          'pcpiShopLog',
          'pcsmpEdit',
          'pcsmTrainValid',
          'pcSingleManage',
          'pcsmTicketEdit',
          'pcpiSiteLog',
          'pcbmThreeCode',
          'merchantCenter',
          'pcsmbDel',
          'pcrsfDel',
          'pcrsTag',
          'pcsmTrainDel',
          'pcbmacEdit',
          'pcpmpmPreView',
          'pcbmacLog',
          'pcsmTicketLog',
          'pcbmsLog',
          'pcrspValid',
          'mcsList',
          'pcpmpmEdit',
          'pcrspEdit',
          'pcrspLog',
          'pcsmHotel',
          'pcbmsValid',
          'pcbmsEdit',
          'pcsmPlane',
          'pcrstEditTag',
          'pcpmpmLog',
          'pcbmacAdd',
          'mcslAdd',
          'pcpiShopAdd',
          'pcsmiLog',
          'pcsmTicketAdd',
          'pcpiShop',
          'pcrstAddTag',
          'pcrsPolicy',
          'pcsmhAdd',
          'pcpifValid',
          'wswApply',
          'pcsmpAdd',
          'pcrsfAddContent',
          'pcbmtcDel',
          'pcsmbEdit',
          'pcrsfValid',
          'pcbmsDel',
          'pcrsfLog',
          'pcsmTicket',
          'mcSupplier',
          'wswApproveDetail',
          'pcsmpValid',
          'pcpiShopEdit',
          'pcsmiEdit',
          'pcsmTrainLog',
          'wsWait'
        ],
        clientId: '',
        companyAbbreviate: '',
        companyId: 0,
        companyName: '',
        deptAbbreviate: '',
        deptId: 0,
        deptName: '',
        expiration: '',
        id: 0,
        mobile: '',
        name: '',
        password: '',
        slCompanyId: 0,
        slCompanyName: '',
        status: 0
      },
      code: '',
      message: ''
    })
  })
}
